name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install npm@7
        run: npm install -g npm@7

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm test
