name: Sync App + Docs

on:
  push:
    branches:
      - main

jobs:
  glitch:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Glitch Project
        uses: kanadgupta/glitch-sync@main
        with:
          project-id: '${{ secrets.projectId }}'
          auth-token: '${{ secrets.authToken }}'

  api-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install deps
        run: npm ci

      - name: Build OpenAPI document
        run: npm run build:openapi

      - name: Sync via rdme
        uses: readmeio/rdme@v8
        with:
          rdme: openapi openapi.json --key ${{ secrets.README_API_KEY }} --id ${{ secrets.README_SPEC_ID }}
