name: flat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Every sixth hour
    - cron: '0 */6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch GeoJSON
        uses: githubocto/flat@v3
        with:
          http_url: https://www.sos.state.mn.us/media/2791/mn-precincts.json
          downloaded_filename: lib/data/mn-precincts.json # The http_url gets saved and renamed in our repository as this file
      - name: Fetch Precinct Table
        uses: githubocto/flat@v3
        with:
          http_url: https://www.sos.state.mn.us/media/3338/precinct-table.xlsx
          downloaded_filename: lib/data/precinct-table.xlsx # The http_url gets saved and renamed in our repository as this file
          postprocess: lib/postprocess.js # A postprocessing javascript or typescript file written in Deno
